/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package KomponentUI;

/**
 *
 * @author LENOVO
 */
public class distribusi_page extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    public distribusi_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanel = new javax.swing.JPanel();
        DataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_tmbh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_scan = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        InputData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_add_input = new javax.swing.JButton();
        btn_batal_input = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        f_telepon = new javax.swing.JTextField();
        f_email = new javax.swing.JTextField();
        f_nmDistribusi = new javax.swing.JTextField();
        f_kodedistribusi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        f_alamat = new javax.swing.JTextArea();

        setLayout(new java.awt.CardLayout());

        Mainpanel.setLayout(new java.awt.CardLayout());

        DataBarang.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Distribusi");

        btn_tmbh.setBackground(new java.awt.Color(153, 153, 255));
        btn_tmbh.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_tmbh.setForeground(new java.awt.Color(255, 255, 255));
        btn_tmbh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Add_properties_30px.png"))); // NOI18N
        btn_tmbh.setText("Tambah");
        btn_tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbhActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Distribusi", "Nama Distribusi", "Alamat", "Nomer Telelpon", "Email", "Barcode"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_scan.setBackground(new java.awt.Color(153, 153, 255));
        btn_scan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_scan.setForeground(new java.awt.Color(255, 255, 255));
        btn_scan.setText("Scan");

        jTextField2.setText("Pencarian");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(153, 153, 255));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_search_28px.png"))); // NOI18N

        javax.swing.GroupLayout DataBarangLayout = new javax.swing.GroupLayout(DataBarang);
        DataBarang.setLayout(DataBarangLayout);
        DataBarangLayout.setHorizontalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(DataBarangLayout.createSequentialGroup()
                        .addComponent(btn_tmbh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_scan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DataBarangLayout.setVerticalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tmbh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_scan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        Mainpanel.add(DataBarang, "card2");

        InputData.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input Distribusi");

        btn_add_input.setBackground(new java.awt.Color(153, 153, 255));
        btn_add_input.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btn_add_input.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Add_properties_30px.png"))); // NOI18N
        btn_add_input.setText("Tambah");
        btn_add_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_inputActionPerformed(evt);
            }
        });

        btn_batal_input.setBackground(new java.awt.Color(153, 153, 255));
        btn_batal_input.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_batal_input.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal_input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_cancel_subscription_30px.png"))); // NOI18N
        btn_batal_input.setText("Batal");
        btn_batal_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_inputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Distribusi");

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nomer Telepon");

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alamat");

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kode Distribusi");

        f_telepon.setBackground(new java.awt.Color(153, 153, 255));
        f_telepon.setBorder(null);
        f_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_teleponActionPerformed(evt);
            }
        });

        f_email.setBackground(new java.awt.Color(153, 153, 255));
        f_email.setBorder(null);
        f_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_emailActionPerformed(evt);
            }
        });

        f_nmDistribusi.setBackground(new java.awt.Color(153, 153, 255));
        f_nmDistribusi.setBorder(null);
        f_nmDistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nmDistribusiActionPerformed(evt);
            }
        });

        f_kodedistribusi.setBackground(new java.awt.Color(153, 153, 255));
        f_kodedistribusi.setBorder(null);
        f_kodedistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_kodedistribusiActionPerformed(evt);
            }
        });

        f_alamat.setBackground(new java.awt.Color(153, 153, 255));
        f_alamat.setColumns(20);
        f_alamat.setRows(5);
        jScrollPane2.setViewportView(f_alamat);

        javax.swing.GroupLayout InputDataLayout = new javax.swing.GroupLayout(InputData);
        InputData.setLayout(InputDataLayout);
        InputDataLayout.setHorizontalGroup(
            InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputDataLayout.createSequentialGroup()
                        .addComponent(f_email, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(f_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addComponent(f_kodedistribusi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InputDataLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(188, 188, 188)
                            .addComponent(jLabel7))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InputDataLayout.createSequentialGroup()
                            .addComponent(btn_add_input, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_batal_input, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(f_nmDistribusi, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputDataLayout.setVerticalGroup(
            InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputDataLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal_input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(5, 5, 5)
                .addComponent(f_kodedistribusi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(f_nmDistribusi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        Mainpanel.add(InputData, "card2");

        add(Mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbhActionPerformed
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        Mainpanel.add(InputData);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_btn_tmbhActionPerformed

    private void btn_add_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_inputActionPerformed

    private void btn_batal_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_inputActionPerformed
 Mainpanel.removeAll();
        
        
        Mainpanel.add(DataBarang);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_btn_batal_inputActionPerformed

    private void f_nmDistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nmDistribusiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nmDistribusiActionPerformed

    private void f_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_emailActionPerformed

    private void f_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_teleponActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void f_kodedistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_kodedistribusiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_kodedistribusiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataBarang;
    private javax.swing.JPanel InputData;
    private javax.swing.JPanel Mainpanel;
    private javax.swing.JButton btn_add_input;
    private javax.swing.JButton btn_batal_input;
    private javax.swing.JButton btn_scan;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_tmbh;
    private javax.swing.JTextArea f_alamat;
    private javax.swing.JTextField f_email;
    private javax.swing.JTextField f_kodedistribusi;
    private javax.swing.JTextField f_nmDistribusi;
    private javax.swing.JTextField f_telepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
