/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package KomponentUI;

import Dao.DAO_barang;
import TableM.TableM_barang;
import java.util.List;
import javax.swing.JOptionPane;
import model.model_barang;
import services.service_barang;

/**
 *
 * @author LENOVO
 */
public class Produk_add_page extends javax.swing.JPanel {

    /**
     * Creates new form Produk_add_page
     */
    private service_barang servis = new DAO_barang();
    private TableM_barang tblMB = new TableM_barang();
    public Produk_add_page() {
        initComponents();
        
        tbl_brg.setModel(tblMB);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanel = new javax.swing.JPanel();
        DataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_tmbh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_brg = new javax.swing.JTable();
        btn_scan = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        InputData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_add_input = new javax.swing.JButton();
        btn_batal_input = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        f_namabarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        f_stok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        f_hargajual = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        f_hargabeli = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        f_kodebarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        Mainpanel.setLayout(new java.awt.CardLayout());

        DataBarang.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Barang");

        btn_tmbh.setBackground(new java.awt.Color(153, 153, 255));
        btn_tmbh.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_tmbh.setForeground(new java.awt.Color(255, 255, 255));
        btn_tmbh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Add_properties_30px.png"))); // NOI18N
        btn_tmbh.setText("Tambah");
        btn_tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbhActionPerformed(evt);
            }
        });

        tbl_brg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_brg.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        tbl_brg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Barang", "Nama Barang", "Harga Jual", "Harga Beli", "Stok", "Kategori"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_brg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_brgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_brg);
        if (tbl_brg.getColumnModel().getColumnCount() > 0) {
            tbl_brg.getColumnModel().getColumn(6).setResizable(false);
        }

        btn_scan.setBackground(new java.awt.Color(153, 153, 255));
        btn_scan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_scan.setForeground(new java.awt.Color(255, 255, 255));
        btn_scan.setText("Scan");
        btn_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scanActionPerformed(evt);
            }
        });

        jTextField2.setText("Pencarian");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(153, 153, 255));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_search_28px.png"))); // NOI18N

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Add_properties_30px.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(153, 153, 255));
        btn_batal.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Add_properties_30px.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataBarangLayout = new javax.swing.GroupLayout(DataBarang);
        DataBarang.setLayout(DataBarangLayout);
        DataBarangLayout.setHorizontalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(DataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DataBarangLayout.createSequentialGroup()
                        .addComponent(btn_tmbh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_scan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DataBarangLayout.setVerticalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tmbh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_scan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        Mainpanel.add(DataBarang, "card2");

        InputData.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input Barang");

        btn_add_input.setBackground(new java.awt.Color(153, 153, 255));
        btn_add_input.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btn_add_input.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Add_properties_30px.png"))); // NOI18N
        btn_add_input.setText("Tambah");
        btn_add_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_inputActionPerformed(evt);
            }
        });

        btn_batal_input.setBackground(new java.awt.Color(153, 153, 255));
        btn_batal_input.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btn_batal_input.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal_input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_cancel_subscription_30px.png"))); // NOI18N
        btn_batal_input.setText("Batal");
        btn_batal_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_inputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Barang");

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stok");

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga Beli");

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harga Jual");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        f_namabarang.setBackground(new java.awt.Color(153, 153, 255));
        f_namabarang.setBorder(null);
        f_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_namabarangActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/name_produk.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(f_namabarang)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(64, 22));

        f_stok.setBackground(new java.awt.Color(153, 153, 255));
        f_stok.setBorder(null);
        f_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_stokActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_sell_stock_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(f_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(64, 22));

        f_hargajual.setBackground(new java.awt.Color(153, 153, 255));
        f_hargajual.setBorder(null);
        f_hargajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_hargajualActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Average_Price_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(f_hargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(f_hargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(64, 22));

        f_hargabeli.setBackground(new java.awt.Color(153, 153, 255));
        f_hargabeli.setBorder(null);
        f_hargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_hargabeliActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/icons8_Average_Price_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(f_hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(f_hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kode Barang");

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        f_kodebarang.setBackground(new java.awt.Color(153, 153, 255));
        f_kodebarang.setBorder(null);
        f_kodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_kodebarangActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/code_brg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(f_kodebarang)
        );

        javax.swing.GroupLayout InputDataLayout = new javax.swing.GroupLayout(InputData);
        InputData.setLayout(InputDataLayout);
        InputDataLayout.setHorizontalGroup(
            InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(InputDataLayout.createSequentialGroup()
                        .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addGroup(InputDataLayout.createSequentialGroup()
                        .addComponent(btn_add_input, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal_input, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        InputDataLayout.setVerticalGroup(
            InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputDataLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal_input, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InputDataLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputDataLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        Mainpanel.add(InputData, "card2");

        add(Mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbhActionPerformed
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        Mainpanel.add(InputData);
        Mainpanel.repaint();
        Mainpanel.revalidate();
           btn_add_input.setText("SIMPAN");
        btn_add_input.setEnabled(true);
        f_kodebarang.setText(servis.nomor());
        if(btn_tmbh.getText().equals("UBAH")){
            dataTabel();
        }
        
    }//GEN-LAST:event_btn_tmbhActionPerformed

    private void btn_add_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_inputActionPerformed
   if(btn_add_input.getText().equals("TAMBAH")){
       btn_add_input.setText("SIMPAN");
       f_kodebarang.setText(servis.nomor());
       
   }else if(btn_add_input.getText().equals("SIMPAN")){
       simpanData();
   }else if(btn_add_input.getText().equals("PERBARUI")){
       perbaruiData();
   }
     
    }//GEN-LAST:event_btn_add_inputActionPerformed

    private void btn_batal_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_inputActionPerformed
tampilPanel();
   loadData();
   resetForm();
    }//GEN-LAST:event_btn_batal_inputActionPerformed

    private void f_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_namabarangActionPerformed

    private void f_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_stokActionPerformed

    private void f_hargajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_hargajualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_hargajualActionPerformed

    private void f_hargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_hargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_hargabeliActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void f_kodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_kodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_kodebarangActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
 hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed

   loadData();
   resetForm();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tbl_brgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_brgMouseClicked
      if(btn_tmbh.getText().equals("TAMBAH")){
          btn_tmbh.setText("UBAH");
      }
      btn_batal.setVisible(true);
      btn_hapus.setVisible(true);
    }//GEN-LAST:event_tbl_brgMouseClicked

    private void btn_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_scanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataBarang;
    private javax.swing.JPanel InputData;
    private javax.swing.JPanel Mainpanel;
    private javax.swing.JButton btn_add_input;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal_input;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_scan;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_tmbh;
    private javax.swing.JTextField f_hargabeli;
    private javax.swing.JTextField f_hargajual;
    private javax.swing.JTextField f_kodebarang;
    private javax.swing.JTextField f_namabarang;
    private javax.swing.JTextField f_stok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbl_brg;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<model_barang> list = servis.ambilData();
        tblMB.setData(list);
    }

    private void simpanData() {
        if(validasiInput()==true){
            String kode_barang = f_kodebarang.getText();
            String nama_barang = f_namabarang.getText();
            int harga_jual =Integer.parseInt(f_hargajual.getText()) ;
            int harga_beli = Integer.parseInt(f_hargabeli.getText());
            long stok = Long.parseLong(f_stok.getText());
        
            
            model_barang brg = new model_barang();
            
            brg.setKode_barang(kode_barang);
            brg.setNama_barang(nama_barang);
            brg.setHarga_beli(harga_beli);
            brg.setHarga_jual(harga_jual);
            brg.setStok(stok);
          
            servis.tambahData(brg);
            tblMB.tambahData(brg);
            loadData();
            resetForm();
            tampilPanel();
            btn_add_input.setText("TAMBAH");
        }
    }

    private void perbaruiData() {
        int index = tbl_brg.getSelectedRow();
        if(index!= -1){
            model_barang mobar = tblMB.getData(tbl_brg.convertRowIndexToModel(index));
            if(validasiInput() == true){
                String kode_barang = f_kodebarang.getText();
                String nama_barang = f_namabarang.getText();
                int harga_beli = Integer.parseInt(f_hargabeli.getText());
                int harga_jual = Integer.parseInt(f_hargajual.getText());
                long stok = Long.parseLong(f_stok.getText());
               
                
                model_barang brg = new model_barang();
                brg.setKode_barang(kode_barang);
                brg.setNama_barang(nama_barang);
                brg.setHarga_beli(harga_beli);
                brg.setHarga_jual(harga_jual);
                brg.setStok(stok);
          
                
                servis.perbaruiData(brg);
                tblMB.perbaruiData(index, brg);
                loadData();
                resetForm();
                tampilPanel();
            }
        }
    }

    private boolean validasiInput() {
       boolean valid = false;
       if(f_kodebarang.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
           
       }else if (f_namabarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong");
        }else if (f_hargabeli.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga Beli tidak boleh kosong");
        }else if (f_hargajual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga Jual tidak boleh kosong");
        }else if (f_stok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong");
        }else{
            valid =true;
        }
       return valid;
    }

    private void resetForm() {
        btn_tmbh.requestFocus();
        btn_tmbh.setText("TAMBAH");
        f_kodebarang.setText("");
         f_namabarang.setText("");
          f_hargajual.setText("");
           f_hargabeli.setText("");
            f_stok.setText("");
      
         
    }

    private void tampilPanel() {
       Mainpanel.removeAll();
       Mainpanel.add(new Produk_add_page());
       Mainpanel.repaint();
       Mainpanel.revalidate();
    }

    private void dataTabel() {
       DataBarang.setVisible(false);
       InputData.setVisible(true);
       
       int row = tbl_brg.getSelectedRow();
       jLabel1.setText("Perbarui Data");
       
       f_kodebarang.setEnabled(false);
       f_kodebarang.setText(tbl_brg.getModel().getValueAt(row, 1).toString());
       f_namabarang.setText(tbl_brg.getModel().getValueAt(row, 2).toString());
       f_hargajual.setText(tbl_brg.getModel().getValueAt(row, 3).toString());
       f_hargabeli.setText(tbl_brg.getModel().getValueAt(row, 4).toString());
       f_stok.setText(tbl_brg.getModel().getValueAt(row, 5).toString());
   
       aktif();
       btn_add_input.setText("PERBARUI");
       btn_batal.setVisible(true);
    }

    private void aktif() {
       f_namabarang.setEnabled(true);
       f_hargabeli.setEnabled(true);
       f_hargajual.setEnabled(true);
       f_stok.setEnabled(true);
     
    }

    private void hapusData() {
        int index = tbl_brg.getSelectedRow();
        if(index !=-1){
            model_barang brg = tblMB.getData(tbl_brg.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Yakin data di hapus?","Kofirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                servis.hapusData(brg);
                tblMB.hapusData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan di update");
        }
    }
}
